### ISSUE TITLE
Das Redmine Jail checkt den falschen logpath

### ISSUE THREAD

**Issue by nce** [vision-it/vision-fail2ban#1]
Das Redmine Jail nimmt als `logpath` den pfad von Apache, sollte aber das Redmine spezifische Log in `/var/log/redmine/default/production.log` ueberwachen.

[Fehler im Template](https://github.com/vision-it/vision-fail2ban/blob/production/templates/jail.conf.erb#L143)

**Comment by martialblog** [comment]
Hoffentlich gefixt in https://github.com/vision-it/vision-fail2ban/commit/c0ac1880423662a4c5a89f7c4d09193b2f9090bf
