### ISSUE TITLE
Restart des fail2ban services nach config Aenderung

### ISSUE THREAD

**Issue by nce** [vision-it/vision-fail2ban#2]
Wenn sich eine fail2ban config datei geaendert hat, muss der service neugestartet werden. Bzw. sollte der Service ueberhaupt erstmal in puppet aufgenommen werden.

**Comment by martialblog** [comment]
Notify und Require hinzugefügt: https://github.com/vision-it/vision-fail2ban/commit/87f43770b87541040370bebffb436633ad8b9f41
